services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: webscraper
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d webscraper" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - webscraper-net

  webscraper:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DATABASE_PORT}/webscraper
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      CHATGPT_API_KEY: ${CHATGPT_API_KEY}
      CHATGPT_BASE_URL: ${CHATGPT_BASE_URL}
      SWAGGER_USERNAME: ${SWAGGER_USERNAME}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      APP_SERVER_URL: ${APP_SERVER_URL}
      APP_SERVER_BACKEND_URL: ${APP_SERVER_BACKEND_URL}
      SHOW_SQL_IN_LOGS: ${SHOW_SQL_IN_LOGS}
      SCRAPER_RESULTS_DIR: ${SCRAPER_RESULTS_DIR}
      LOGS_DIR: ${LOGS_DIR}
      LOG_LEVEL_CONSOLE: ${LOG_LEVEL_CONSOLE}
      LOG_LEVEL_FILE: ${LOG_LEVEL_FILE}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - webscraper-net

volumes:
  db_data:

networks:
  webscraper-net: